config/routes.rb
Lostandfound::Application.routes.draw do
  resources :turkishes

  resources :items
  
  resources :items do
    collection do
      get 'search'
    end
  end

end

app/models/american.rb
class American < Item
  def set_type 
    self.type = 'American'
  end
end

app/models/french.rb
class French < Item
  def set_type 
    self.type = 'French'
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

  self.inheritance_column = nil


  def self.subclasses
    [Turkish, French, American]
  end




  def self.search(search)
    search_condition = "%" + search.to_s + "%"
    find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
  end
end

app/models/turkish.rb
class Turkish < ActiveRecord::Base
  def set_type 
    self.type = 'Turkish'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json

def index
  @items = Item.search(params[:search])
end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    @search_items = Item.search(params[:search])
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :type)
    end
end

app/controllers/turkishes_controller.rb
class TurkishesController < ApplicationController
  before_action :set_turkish, only: [:show, :edit, :update, :destroy]

  # GET /turkishes
  # GET /turkishes.json
  def index
    @turkishes = Turkish.all
  end

  # GET /turkishes/1
  # GET /turkishes/1.json
  def show
  end

  # GET /turkishes/new
  def new
    @turkish = Turkish.new
  end

  # GET /turkishes/1/edit
  def edit
  end

  # POST /turkishes
  # POST /turkishes.json
  def create
    @turkish = Turkish.new(turkish_params)

    respond_to do |format|
      if @turkish.save
        format.html { redirect_to @turkish, notice: 'Turkish was successfully created.' }
        format.json { render action: 'show', status: :created, location: @turkish }
      else
        format.html { render action: 'new' }
        format.json { render json: @turkish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turkishes/1
  # PATCH/PUT /turkishes/1.json
  def update
    respond_to do |format|
      if @turkish.update(turkish_params)
        format.html { redirect_to @turkish, notice: 'Turkish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @turkish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turkishes/1
  # DELETE /turkishes/1.json
  def destroy
    @turkish.destroy
    respond_to do |format|
      format.html { redirect_to turkishes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turkish
      @turkish = Turkish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turkish_params
      params.require(:turkish).permit(:title, :description, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/turkishes_helper.rb
module TurkishesHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%#= f.select :item_type_id, @item_types.collect{|p| [p.name, p.id] }, params[:item_type_id] %>
  <select name="item[type]">
    <option value="">Please select</option>
    <option value="Turkish" selected="selected">Turkish</option>
    <option value="American">American</option>
    <option value="French">French</option>
  </select>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_search.html.erb
  </br></br>
  <%= form_tag :controller => 'items', :action => 'search', :method => 'get' do %>
2      <%= text_field_tag :search, params[:search], :id => 'search_field' %>
3      <%= submit_tag "Search", :name => nil %> 
4      <%= link_to_function "Clear", "$('search_field').clear()" %>
5  <% end %> 

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.type %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>


 <div id="search">
    <%= render :partial => 'items/search' %>
  </div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @item.type %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lostandfound</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>



</body>
</html>

app/views/turkishes/_form.html.erb
<%= form_for(@turkish) do |f| %>
  <% if @turkish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turkish.errors.count, "error") %> prohibited this turkish from being saved:</h2>

      <ul>
      <% @turkish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/turkishes/edit.html.erb
<h1>Editing turkish</h1>

<%= render 'form' %>

<%= link_to 'Show', @turkish %> |
<%= link_to 'Back', turkishes_path %>

app/views/turkishes/index.html.erb
<h1>Listing turkishes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @turkishes.each do |turkish| %>
      <tr>
        <td><%= turkish.title %></td>
        <td><%= turkish.description %></td>
        <td><%= turkish.type %></td>
        <td><%= link_to 'Show', turkish %></td>
        <td><%= link_to 'Edit', edit_turkish_path(turkish) %></td>
        <td><%= link_to 'Destroy', turkish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turkish', new_turkish_path %>

app/views/turkishes/new.html.erb
<h1>New turkish</h1>

<%= render 'form' %>

<%= link_to 'Back', turkishes_path %>

app/views/turkishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @turkish.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @turkish.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @turkish.type %>
</p>

<%= link_to 'Edit', edit_turkish_path(@turkish) %> |
<%= link_to 'Back', turkishes_path %>